// Zero-knowledge secret-sharing crypto helpers. The server never sees
// plaintext, an unwrapped content key, or a passphrase — everything in this
// module runs client-side only. Mirrors admin-web/src/lib/crypto.ts's wire
// format exactly: wrappedContentKey is base64(iv(12B) || gcmCiphertext).

const CONTENT_KEY_ALGORITHM = "AES-GCM";
const CONTENT_KEY_LENGTH_BITS = 256;

/** Length, in bytes, of every AES-GCM IV used by this module. */
export const IV_LENGTH_BYTES = 12;
/** Length, in bytes, of every PBKDF2 salt generated by deriveWrappingKey. */
export const SALT_LENGTH_BYTES = 16;
/** Floor enforced by the spec: PBKDF2-SHA256 MUST use at least this many iterations. */
export const MIN_KDF_ITERATIONS = 210_000;
/** Iteration count used when a caller does not request a specific value. */
export const DEFAULT_KDF_ITERATIONS = MIN_KDF_ITERATIONS;

export function base64Encode(bytes: ArrayBuffer | Uint8Array): string {
  const view = bytes instanceof Uint8Array ? bytes : new Uint8Array(bytes);
  let binary = "";
  for (const byte of view) {
    binary += String.fromCharCode(byte);
  }
  return btoa(binary);
}

export function base64Decode(value: string): Uint8Array<ArrayBuffer> {
  const binary = atob(value);
  const bytes = new Uint8Array(binary.length);
  for (let index = 0; index < binary.length; index += 1) {
    bytes[index] = binary.charCodeAt(index);
  }
  return bytes;
}

/** Generates a new random AES-256-GCM content key, extractable so it can be exported into a share link's fragment. */
export async function generateContentKey(): Promise<CryptoKey> {
  return crypto.subtle.generateKey({ name: CONTENT_KEY_ALGORITHM, length: CONTENT_KEY_LENGTH_BITS }, true, ["encrypt", "decrypt"]);
}

/** Exports a content key to its raw base64 form, for placing in a share link's URL fragment. */
export async function exportContentKey(key: CryptoKey): Promise<string> {
  const raw = await crypto.subtle.exportKey("raw", key);
  return base64Encode(raw);
}

/** Re-imports a content key from the raw base64 form carried in a share link's URL fragment. */
export async function importContentKey(base64Key: string): Promise<CryptoKey> {
  const raw = base64Decode(base64Key);
  return crypto.subtle.importKey("raw", raw, { name: CONTENT_KEY_ALGORITHM }, true, ["encrypt", "decrypt"]);
}

/** Encrypts plaintext with key, returning base64 ciphertext and a fresh random base64 IV. */
export async function encrypt(key: CryptoKey, plaintext: string): Promise<{ ciphertext: string; iv: string }> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH_BYTES));
  const encoded = new TextEncoder().encode(plaintext);
  const buffer = await crypto.subtle.encrypt({ name: CONTENT_KEY_ALGORITHM, iv }, key, encoded);
  return { ciphertext: base64Encode(buffer), iv: base64Encode(iv) };
}

/** Decrypts a base64 ciphertext/iv pair produced by encrypt. Rejects on GCM auth-tag mismatch. */
export async function decrypt(key: CryptoKey, ciphertext: string, iv: string): Promise<string> {
  const buffer = await crypto.subtle.decrypt({ name: CONTENT_KEY_ALGORITHM, iv: base64Decode(iv) }, key, base64Decode(ciphertext));
  return new TextDecoder().decode(buffer);
}

export interface WrappingKeyResult {
  key: CryptoKey;
  /** base64-encoded salt — persist this as passphraseSalt. */
  salt: string;
  iterations: number;
}

/**
 * Derives an AES-256-GCM key-wrapping key from a passphrase via
 * PBKDF2-SHA256. When saltBase64 is omitted, a fresh random salt is
 * generated (creation flow); pass the persisted passphraseSalt back in to
 * re-derive the same key on reveal.
 */
export async function deriveWrappingKey(passphrase: string, saltBase64?: string, iterations: number = DEFAULT_KDF_ITERATIONS): Promise<WrappingKeyResult> {
  const salt = saltBase64 ? base64Decode(saltBase64) : crypto.getRandomValues(new Uint8Array(SALT_LENGTH_BYTES));

  const keyMaterial = await crypto.subtle.importKey("raw", new TextEncoder().encode(passphrase), { name: "PBKDF2" }, false, ["deriveKey"]);

  const key = await crypto.subtle.deriveKey(
    { name: "PBKDF2", salt, iterations, hash: "SHA-256" },
    keyMaterial,
    { name: CONTENT_KEY_ALGORITHM, length: CONTENT_KEY_LENGTH_BITS },
    false,
    ["wrapKey", "unwrapKey"],
  );

  return { key, salt: base64Encode(salt), iterations };
}

/**
 * Wraps contentKey with wrappingKey, returning the wire format
 * base64(iv(12B) || gcmCiphertext) for the wrappedContentKey field.
 */
export async function wrapKey(wrappingKey: CryptoKey, contentKey: CryptoKey): Promise<string> {
  const iv = crypto.getRandomValues(new Uint8Array(IV_LENGTH_BYTES));
  const wrapped = await crypto.subtle.wrapKey("raw", contentKey, wrappingKey, { name: CONTENT_KEY_ALGORITHM, iv });

  const combined = new Uint8Array(iv.length + wrapped.byteLength);
  combined.set(iv, 0);
  combined.set(new Uint8Array(wrapped), iv.length);

  return base64Encode(combined);
}

/**
 * Unwraps a wrappedContentKey produced by wrapKey. Rejects with a GCM
 * auth-tag mismatch (never returns silent garbage) when wrappingKey does not
 * match — e.g. a wrong passphrase.
 */
export async function unwrapKey(wrappingKey: CryptoKey, wrappedContentKey: string): Promise<CryptoKey> {
  const combined = base64Decode(wrappedContentKey);
  const iv = combined.slice(0, IV_LENGTH_BYTES);
  const wrapped = combined.slice(IV_LENGTH_BYTES);

  return crypto.subtle.unwrapKey(
    "raw",
    wrapped,
    wrappingKey,
    { name: CONTENT_KEY_ALGORITHM, iv },
    { name: CONTENT_KEY_ALGORITHM, length: CONTENT_KEY_LENGTH_BITS },
    true,
    ["encrypt", "decrypt"],
  );
}
