export const ROOT_FOLDER_TITLE = "Shared Bookmarks";
export const DEFAULT_BACKEND_URL = "http://localhost:8081";
export const STORAGE_KEY = "sharedBookmarkSyncState";
export const DIAGNOSTIC_LIMIT = 50;
export const CLIENT_ID_HEADER = "X-Client-Id";
export const SYNC_EVENT_ID_HEADER = "X-Sync-Event-Id";
export const SYNC_BASE_CURSOR_HEADER = "X-Sync-Base-Cursor";
export const SYNC_CURSOR_HEADER = "X-Sync-Cursor";
export const SYNC_DUPLICATE_HEADER = "X-Sync-Duplicate";
